version: "3"
services:
  icecast:
    environment:
      - ICECAST_ADMIN_PASSWORD=admin1337
      - ICECAST_PASSWORD=pass1337
      - ICECAST_RELAY_PASSWORD=relay1337
      - ICECAST_SOURCE_PASSWORD=src1337
    image: moul/icecast:latest
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
  liquidsoap:
    environment:
      - ICECAST_HOST=icecast
      - ICECAST_PORT=8000
      - ICECAST_SOURCE_PASSWORD=src1337
    command: liquidsoap -v --debug /liquidsoap/liquidsoap.liq
    image: moul/liquidsoap:latest
    ports:
      - 8800:8800
    user: liquidsoap
    volumes:
      - ./liquidsoap.liq:/liquidsoap/liquidsoap.liq
      - ./music:/data
      - /etc/localtime:/etc/localtime:ro
